@startuml vdap_audit_log
allowmixing
left to right direction

json Audit_Log {
    "time": "time", 
    "id": "uuid", 
    "userId": "userId",
    "sessionId": "sessionId", 
    "authorizeId": "athorizedId",
    "resource": {
        "id": "resource ID",
        "uri": "uri"
    },
    "action": ["read(get)", "write(post)"],
    "result": ["success", "fail(error)"],
    "reason": "fail(error) reason"
}

actor User

usecase "ResourceAccess" as res_access
usecase "UserManagement" as user_management
usecase "AuditLog" as audit
usecase "Modify\nUserInfo" as user_modify
usecase "Withdraw\nMembership" as withdraw

user_management <-- audit 
user_management <-- user_modify
user_management <-- withdraw

User --> res_access
User --> user_management

res_access -right-> write_audit_log

@enduml
