@startuml vdap_virtualization
allowmixing
left to right direction
actor User

note "저장소 가상화 권한을 가진 사용자" as member_info

member_info .. User

usecase "Storage\nManagement" as Storage
usecase "List" as list
usecase "Add" as add
usecase "Del" as del
usecase "Modify" as modify
Storage <-- list
Storage <-- add
Storage <-- del
Storage <-- modify

json Service {
  "id": "uuid"
}

' 기존 오픈메타데이터의 경우 저장소 등록 시 자동으로 메타데이터/프로파일러 수집 파이프라인이 등록되지 않았음.
' 따라서 신규 버전에서는 기본 정보 이력 후 고급설정으로 넘어가는 단계를 추가하여 파이프라인을 설정하거나,
' 기본 설정에 따라 메타데이터/프로파일러/모니터링이 동작할 수 있도록 한다. 

usecase "Storage\nSetting" as Setting
usecase "Metadata\nSetting" as metadata
usecase "Profiler\nSetting" as profiler
usecase "Monitoring\nSetting" as monitoring_set
usecase "AccessControl" as access_control

Setting <-- metadata
Setting <-- profiler
Setting <-- monitoring_set
Setting <-- access_control

' 메타데이터 수집 데이터
json MetadataPipeline {
  "id": "uuid"
}
' 프로파일러 설정 
json ProfilerPipeline {
  "id": "uuid"
}
' 샘플 수집 설정
json SamplerPipeline {
  "id": "uuid"
}

usecase "StorageExplorer" as Explorer
usecase "List" as e_list
usecase "Search" as e_search
usecase "Expend" as e_expend
usecase "Collapse" as e_collapse

Explorer <-- e_list
Explorer <-- e_search
Explorer <-- e_expend
Explorer <-- e_collapse

' Explorer 는 저장소 내 데이터(메타데이터) 탐색기이다.
' 이름을 검새과 저장소 타입, 내가 설정한 즐겨찾기를 이용한 필터링 기능을 같이 제공한다.

User --> Storage
User --> Setting
User --> Explorer

json ExplorerExpendReq {
  "sourcePath": "/",
  "depth": 1
}

json ExplorerRes {
  "child list": [
    {
      "type": ["database", "objectStorage", "table", "file", "etc"],
      "id": "depth_01_data_id",
      "name": "depth_01_data_name",
      "uri": "depth_01_data_uri",
      "child": ["child list"]
    }
  ]
}

json ExplorerSearchReq {
  "name": "storage name",
  "storageType": ["database", "objectStorage", "etc"],
  "myFavorites": ["true", "false"]
}

' 탐색기 창 클릭 이벤트 별 처리가 중요
' `+, -` 클릭 or (데이터 더블 클릭) 시 `expend` 와 `collapse` 동작
' 데이터 클릭 시 uri를 이용해 화면에 데이터 정보 보여주기 

@enduml
