openapi: "3.0.2"
info:
  title: Data Fabric Rest API Doc
  version: "1.0.0"
servers:
  - url: http://192.168.106.1:33080
paths:
  ## 데이터 패브릭 - 검색
  /portal/v1/search:
    description: "데이터/저장소 검색"
    post:
      tags:
        - "portal"
      requestBody:
        $ref: "./requests/__index.yaml#/Search"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/Search"
  ## 데이터 패브릭 - 최근 검색어
  /portal/v1/recent-searches:
    description: "사용자 최근 검색어"
    get:
      tags:
        - "portal"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/RecentSearches"
  ## 데이터 카탈로그 - 미리보기
  /data/v1/preview:
    description: "데이터 미리보기"
    post:
      tags:
        - "data"
      requestBody:
        $ref: "./requests/__index.yaml#/DataCatalogId"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/DataPreview"
  ## 상세보기 - 기본정보
  /data/v1/default:
    description: "데이터 상세 보기 - 기본 정보"
    get:
      tags:
        - "data"
      requestBody:
        $ref: "./requests/__index.yaml#/DataCatalogId"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/DataDefault"
  # 사용자 메타 데이터 업데이트
  /data/v1/metadata:
    description: >
      메타데이터 업데이트
      기존 데이터에서 신규/수정/삭제에 따라 변화된 사용자 메타 데이터 전체를 업데이트한다.
    post:
      tags:
        - "data"
      requestBody:
        $ref: "./requests/__index.yaml#/DataMetaUpdate"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/DataMetaUpdate"
  # 태그 업데이트
  /data/v1/tag:
    description: >
      태그 업데이트
      기존 데이터에서 신규/수정/삭제에 따라 변화된 사용자 태그 전체를 업데이트한다.
    post:
      tags:
        - "data"
      requestBody:
        $ref: "./requests/__index.yaml#/DataTagUpdate"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/DataTagUpdate"
  # 다운로드 요청
  /data/v1/download-request:
    description: 다운로드 요청
    post:
      tags:
        - "data"
      requestBody:
        $ref: "./requests/__index.yaml#/DataCatalogId"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/DataDownloadRequest"
  # 다운로드
  /data/v1/download/{DownloadId}:
    description: 데이터에 포함된 다운로드 링크
    get:
      tags:
        - "data"
      parameters:
        - name: DownloadId
          in: path
          description: 다운로드 아이디
          required: true
          schema:
            type: string
      responses:
        '200':
          description: >
            ZIP 압축 파일을 전송. 
            테이블 형태의 데이터는 CSV
            일반 데이터는 원본과 동일한 포맷으로 전달
          content:
            application/zip:
              schema:
                type: string
                format: binary
  # 데이터 평가와 코멘트
  /data/v1/comment/add:
    description: "데이터 평가와 댓글 추가"
    post:
      tags:
        - "data"
      requestBody:
        $ref: "./requests/__index.yaml#/DataRatingAndComment"
      responses:
        200:
          $ref: "./responses/__index.yaml#/RatingAndComment"
  /data/v1/comment/update:
    description: "데이터 평가와 댓글 수정"
    post:
      tags:
        - "data"
      requestBody:
        $ref: "./requests/__index.yaml#/DataRatingAndComment"
      responses:
        200:
          $ref: "./responses/__index.yaml#/RatingAndComment"
  /data/v1/comment/delete:
    description: "데이터 평가와 댓글 삭제"
    post:
      tags:
        - "data"
      requestBody:
        $ref: "./requests/__index.yaml#/DataRatingAndComment"
      responses:
        200:
          $ref: "./responses/__index.yaml#/RatingAndComment"

  ## 저장소 탐색
  /storage/v1/overview:
    description: "저장소 대시보드"
    get:
      tags:
        - "storage"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/StorageOverview"
  /storage/v1/search:
    description: "저장소 검색(저장소 목록 조회)"
    post:
      tags:
        - "storage"
      requestBody:
        $ref: "./requests/__index.yaml#/StorageSearch"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/StorageSearch"
        '401':
          description: Unauthorized
  /storage/v1/status:
    description: "저장소 상태 정보"
    post:
      tags:
        - "storage"
      requestBody:
        $ref: "./requests/__index.yaml#/StorageId"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/StorageStatus"
  /storage/v1/default:
    description: "저장소 기본 정보"
    post:
      tags:
        - "storage"
      requestBody:
        $ref: "./requests/__index.yaml#/StorageId"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/StorageDefault"
  /storage/v1/advanced:
    description: "저장소 고급(수집) 설정 정보"
    post:
      tags:
        - "storage"
      requestBody:
        $ref: "./requests/__index.yaml#/StorageId"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/StorageAdvanced"
  /storage/v1/browse:
    description: "저장소 내 테이블(파일) 탐색"
    post:
      tags:
        - "storage"
      requestBody:
        $ref: "./requests/__index.yaml#/StorageBrowse"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/StorageBrowse"
  /storage/v1/browse/default:
    description: "저장소 내 사용자가 선택한 테이블(파일)의 기본 정보"
    post:
      tags:
        - "storage"
      requestBody:
        $ref: "./requests/__index.yaml#/StorageBrowse"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/StorageDataDefault"
  /storage/v1/browse/data-view:
    description: "저장소 내 사용자가 선택한 테이블(파일)의 데이터 보기 - 1차 미제공"
    post:
      tags:
        - "storage"
      requestBody:
        $ref: "./requests/__index.yaml#/StorageBrowse"
      responses:
        '200':
          description: OK

  # 저장소 연결 정보 관리 Storage Connection Info Management
  /storage/v1/storage-type:
    description: > 
      시스템에서 연결을 지원하는 저장소 타입 조회
      API PATH 변경될 수 있음
    get:
      tags:
        - "storage-management"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/SupportedStorageType"
  /storage/v1/adaptors:
    description: >
      선택한 저장소 타입의 드라이버 리스트 조회
      드라이버 리스트 별 연결에 필요한 입력 필드 정보를 포함한다.
    get:
      tags:
        - "storage-management"
      parameters:
        - in: query
          name: storage-type
          description: "저장소 타입"
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: "./responses/__index.yaml#/Adaptor"
  /storage/v1/connect-test:
    description: >
      선택한 저장소 타입(어댑터[JDBC])에 맞춰 사용자 입력을 확인하고 연결 테스트를 진행한다.
    post:
      tags:
        - "storage-management"
      requestBody:
        $ref: "./requests/__index.yaml#/ConnectTest"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/ConnectTest"
  /storage/v1/add:
    description: >
      연결 테스트를 완료한 연결 정보의 저장
      기본 정보(이름, 설명, 메타, 태그) 연결 정보(어탭터, 연결 옵션), 고급(수집) 설정 정보를 저장한다.
    post:
      tags:
        - "storage-management"
      requestBody:
        $ref: "./requests/__index.yaml#/AddStorage"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/AddStorage"
  /storage/v1/modify:
    description: >
      저장소 연결 정보 수정
      기본 정보(이름, 설명, 메타, 태그) 연결 정보(어탭터, 연결 옵션), 고급(수집) 설정 정보를 수정한다.
    post:
      tags:
        - "storage-management"
      requestBody:
        $ref: "./requests/__index.yaml#/ModifyStorage"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/ModifyStorage"
  /storage/v1/connected-data/{storageId}:
    description: >
      연결정보(저장소) 삭제 전 연결된 데이터를 확인하는 API
    get:
      tags:
        - "storage-management"
      parameters:
        - name: storageId
          in: path
          description: "저장소 ID"
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: "./responses/__index.yaml#/ConnectedData"
  /storage/v1/delete:
    description: 연결정보(저장소) 삭제
    post:
      tags:
        - "storage-management"
      requestBody:
        $ref: "./requests/__index.yaml#/StorageId"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/DeleteStorage"

  # 저장소 유형과 어탭터 관리 관련 내용은 12월 개발
#  /storage/v1/storage-type/schema:
#    description: "저장소 유형에 따라 요구되는 입력 정보 조회"
#    get:
#      tags:
#        - "Management : Supported Storage And Adaptor(Driver)"
#      responses:
#        '200':
#          $ref: "#/components/responses/SupportedStorageTypeSchemaResponse"

  # 데이터 탐색기
  /data/v1/all-data/summary:
    description: "시스템 내 전체 데이터 조회 - 요약된 데이터 정보를 전달(좌측 패널 출력을 목적으로 함)"
    post:
      tags:
        - data-browser
      requestBody:
        $ref: "./requests/__index.yaml#/DataCatalogSearch"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/DataBrowserAllDataSummary"
  /data/v1/all-data:
    description: "시스템 내 전체 데이터를 조회"
    post:
      tags:
        - data-browser
      requestBody:
        $ref: "./requests/__index.yaml#/DataCatalogSearch"
      responses:
        '200':
          $ref: "./responses/__index.yaml#/DataBrowser"

        # 인증 관련
security:
  - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    $ref: "./parameters/__index.yaml"
  requestBodies:
    $ref: "./requests/__index.yaml"
  responses:
    $ref: "./responses/__index.yaml"
  schemas:
    $ref: "./schemas/__index.yaml"
