SELECT
    SUM(CASE WHEN VARIABLE_NAME LIKE 'Aborted_%' THEN VARIABLE_VALUE ELSE 0 END) AS failed_queries,
    SUM(CASE WHEN VARIABLE_NAME LIKE 'Com_%' THEN VARIABLE_VALUE ELSE 0 END) AS success_queries
FROM INFORMATION_SCHEMA.GLOBAL_STATUS;