/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mobigen.datafabric.sample;

import com.mobigen.libs.list.LinkedList;
import org.apache.commons.text.WordUtils;

import static com.mobigen.datafabric.sample.MessageUtils.getMessage;
import static com.mobigen.utilities.list.StringUtils.join;
import static com.mobigen.utilities.list.StringUtils.split;

public class Sample{
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
