server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: "/new-spring-boot-sample"
  tomcat:
    threads:
      max: 20

logging:
  level:
    root: "info"
    #org.springframework: "info"
    #java.net: "debug"


spring:
  application:
    name: new-spring-boot
#  config:
#    import: "configserver:${CONFIG_SERVER_URL}"
#  rabbitmq:
#    host: ${MQ_URL}
#    port: ${MQ_PORT}
#    username: ${MQ_USER}
#    password: ${MQ_PASSWORD}
#  datasource:
#    url: "jdbc:mariadb://${DB_URL}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    hikari:
#      connection-test-query: SELECT 1
#      minimum-idle: 20
#      maximum-pool-size: 20
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDB103Dialect
#    show-sql: false
#    hibernate:
#      ddl-auto: validate
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: false
#        jdbc: "time_zone=UTC"
#  #        globally_quoted_identifiers: true
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#  lifecycle:
#    timeout-per-shutdown-phase: 5s
#  messages:
#    basename: "i18n/message"
#    encoding: "UTF-8"

otel:
# service.name: 설정하지 않을 경우 spring.application.name 을 사용 함.
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://${JAEGER_HOST:jaeger-svc}:${JAEGER_PORT:4317}
  traces:
    exporter: otlp
  # jaeger : log, metric 수집을 지원하지 않음.
  logs:
    exporter: none
  metrics:
    exporter: none
